spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-46-137-156-205.eu-west-1.compute.amazonaws.com:5432/d85lvg62mtem5f
    username: fghpwhptiqrowe
    password: 643eca59b44bb0df52d1d5b39c12fbe2817565e1692d22faa28c88d3da4f2770
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
server:
  port : 8080
amazonProperties:
  endpointUrl: https://s3.eu-west-3.amazonaws.com
  accessKey: AKIAU53YH6NXXVGGNFP5
  secretKey: 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
  bucketName: webdistantion
  region: eu-west-3